---
- name: Bootstrap dev tools
  hosts: all

  vars_files:
    - config/local.yml
    - ~/projects/itstommymorgan/dotfiles/config.yml

  pre_tasks:
    - import_tasks: tasks/sudoer.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.dotfiles

  tasks:
    - name: Register current hostname
      ansible.builtin.shell: hostname
      register: current_hostname
    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{ locals.hostname }}"
      when: current_hostname.stdout != locals.hostname

    - name: Detect CPU Type
      ansible.builtin.command: uname -m
      register: cpu_type

    - name: Install Rosetta
      ansible.builtin.command: softwareupdate --install-rosetta --agree-to-license
      when: cpu_type.stdout.find('arm64') != -1

    - name: Create company projects folder
      ansible.builtin.command: mkdir -p ~/projects/{{ locals.company_name }}
      when: locals.company_name != ""

- name: Homebrew and Ruby
  hosts: all

  vars_files:
    - config/homebrew.yml
    - config/rbenv.yml

  roles:
    - role: geerlingguy.mac.homebrew
    - role: zzet.rbenv

- name: PGP setup and decryption
  hosts: all

  tasks:
    - name: Register public key list
      ansible.builtin.command: gpg --list-keys
      register: public_key_list
    - name: Register private key list
      ansible.builtin.command: gpg --list-secret-keys
      register: private_key_list
    - name: Import public key
      ansible.builtin.command: op read op://Private/pgp/public | gpg --import
      when: public_key_list.stdout.find('tommy@tommymorgan.name') == -1
    - name: Import private key
      ansible.builtin.command: op read op://Private/pgp/private | gpg --import
      when: private_key_list.stdout.find('tommy@tommymorgan.name') == -1
    - name: Decrypt the repository
      ansible.builtin.command: git-crypt unlock

- name: Mac configuration
  hosts: all

  vars_files:
    - config/dock.yml
    - config/mas.yml
    - config/startup_apps.yml

  roles:
    - role: geerlingguy.mac.homebrew
    - role: geerlingguy.mac.dock
    - role: geerlingguy.mac.mas

  tasks:
    - import_tasks: tasks/startup_apps.yml

- name: Install Package Manager Dependencies
  hosts: all

  vars_files:
    - config/packages.yml

  environment:
    PATH: ~/.rbenv/shims:{{ ansible_env.PATH }}

  tasks:
    - import_tasks: tasks/extra-packages.yml

- name: Remind about any manual steps that need to be performed
  hosts: all

  tasks:
    - name: Register Vimcal path
      stat:
        path: /Applications/Vimcal
      register: vimcal_path
    - name: Check Vimcal
      ansible.builtin.command: echo "Install Vimcal - https://www.vimcal.com/downloads/mac-m1"
      when: vimcal_path.stat.exists
