---

dotfiles_repo: git@github.com:itstommymorgan/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/projects/itstommymorgan/dotfiles
dotfiles_repo_version: main
dotfiles_files:
  - .config
  - .hammerspoon
  - .oh-my-zsh
  - .tmux
  - .tmuxinator
  - .zsh
  - .gvimrc
  - .rubocop.yml
  - .tmux.conf
  - .zshenv
  - .zshrc
