# Homebrew packages
homebrew_installed_packages:
  - awscli
  - bat
  - curl
  - ctags
  - diff-so-fancy
  - exa
  - git
  - git-crypt
  - gnupg
  - hub
  - jq
  - loginitems
  - mosquitto
  - neovim
  - nvm
  - postgresql@14
  - rbenv
  - redis
  - ripgrep
  - shellcheck
  - the_silver_searcher
  - tmux
  - tmuxinator
  - tree-sitter
  - zoxide
  - zplug
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - OJFord/formulae
  - wez/wezterm

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-fira-code-nerd-font
  - google-chrome
  - hammerspoon
  - hiddenbar
  - karabiner-elements
  - keybase
  - obsidian
  - raycast
  - signal
  - slack
  - spotify
  - soulver
  - todoist
  - wezterm
  - whatsapp
  - zoom
